name: dbt CI
on:
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: ./dbt_101
      # DBT_PROFILES_DIR: ./profiles
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}_${{ github.event.number }}
      SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
      SNOWFLAKE_CI_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CI_USER_PRIVATE_KEY }}
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dbt
        run: |
          pip install sqlfluff dbt-core dbt-snowflake
          dbt deps
      
      - name: Run dbt tests
        run: sqlfluff lint .

      - name: Install dbt
        run: |
          pip install -r requirements.txt
          dbt deps
      
      - name: Run dbt tests
        run: dbt build --target ci
